### ISSUE TITLE
Undefined variable: api (8)

### ISSUE THREAD

**Issue by clarkey** [flightphp/core#171]
Hi,

I get the following error when running this..

```
 500 Internal Server Error
 Undefined variable: api (8)

#0 D:\Sites\PSO\WWW\api\arc\v2\index.php(15): flight\Engine->handleError(8, 'Undefined varia...', 'D:\\Sites\\PSO\\WW...', 15, Array)
#1 D:\Sites\PSO\WWW\api\arc\v2\flight\core\Dispatcher.php(160): {closure}()
#2 D:\Sites\PSO\WWW\api\arc\v2\flight\core\Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#3 D:\Sites\PSO\WWW\api\arc\v2\flight\Engine.php(312): flight\core\Dispatcher::execute(Object(Closure), Array)
#4 D:\Sites\PSO\WWW\api\arc\v2\flight\core\Dispatcher.php(191): flight\Engine->_start()
#5 D:\Sites\PSO\WWW\api\arc\v2\flight\core\Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#6 D:\Sites\PSO\WWW\api\arc\v2\flight\core\Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#7 D:\Sites\PSO\WWW\api\arc\v2\flight\Engine.php(64): flight\core\Dispatcher->run('start', Array)
#8 D:\Sites\PSO\WWW\api\arc\v2\index.php(26): flight\Engine->__call('start', Array)
#9 D:\Sites\PSO\WWW\api\arc\v2\index.php(26): flight\Engine->start()
#10 {main}
```

This is the code...

```
# Load Flight (http://flightphp.com)
# Load Sparrow (https://github.com/mikecao/sparrow)
require('flight/autoload.php');
use flight\Engine;
require('sparrow/Sparrow.php');

# Initialise Flight & Sparrow
$api = new Engine();
$db = new Sparrow();

# API Route: Default
$api->route('/', function() {
  $api->halt();
});

# Lets go!
$api->start();
```

The default usage with the static methods work fine, but I'd rather use the framework as objects.

**Comment by jimlei** [comment]
The function acts as an isolated scope so pass in the $api variable to have it available there as well.

```
$api->route('/', function() use ($api) {
  $api->halt();
});
```

**Comment by clarkey** [comment]
@jimlei that works perfectly - thank you!
