### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by rsenses** [flightphp/core#220]
I´m using Sentry to manage users. This is the example to create a user:

``` php
try
{
    // Create the user
    $user = Sentry::createUser(array(
        'email'     => 'john.doe@example.com',
        'password'  => 'test',
        'activated' => true,
    ));

    // Find the group using the group id
    $adminGroup = Sentry::findGroupById(1);

    // Assign the group to the user
    $user->addGroup($adminGroup);
}
catch (Cartalyst\Sentry\Users\LoginRequiredException $e)
{
    echo 'Login field is required.';
}
catch (Cartalyst\Sentry\Users\PasswordRequiredException $e)
{
    echo 'Password field is required.';
}
catch (Cartalyst\Sentry\Users\UserExistsException $e)
{
    echo 'User with this login already exists.';
}
catch (Cartalyst\Sentry\Groups\GroupNotFoundException $e)
{
    echo 'Group was not found.';
}
```

When Sentry throw an exception Flight sends an HTTP 500 response. What i want is to send the error message to a Flight view. I don't know how to do it.
I've tried mapping error, but Flight stops.

Thanks

**Comment by jimlei** [comment]
You should be able to do that, are you sure you are catching all errors?

try to change to this, since all exceptions extend \Exception you should now catch any exception in the block. You can use the exception itself ($e) to get more information on what has happened.

``` php
try
{
    // Create the user
    $user = Sentry::createUser(array(
        'email'     => 'john.doe@example.com',
        'password'  => 'test',
        'activated' => true,
    ));

    // Find the group using the group id
    $adminGroup = Sentry::findGroupById(1);

    // Assign the group to the user
    $user->addGroup($adminGroup);
}
catch (Cartalyst\Sentry\Users\LoginRequiredException $e)
{
    echo 'Login field is required.';
}
catch (Cartalyst\Sentry\Users\PasswordRequiredException $e)
{
    echo 'Password field is required.';
}
catch (Cartalyst\Sentry\Users\UserExistsException $e)
{
    echo 'User with this login already exists.';
}
catch (Cartalyst\Sentry\Groups\GroupNotFoundException $e)
{
    echo 'Group was not found.';
}
catch (\Exception $e)
{
     echo 'Generic error, how did we end up here? What\'s wrong? Who knows?';
     print_r($e->getTrace());
}
```

You seem to be missing a few Exceptions in your list

``` php
try
{
    // Login credentials
    $credentials = array(
        'email'    => 'john.doe@example.com',
        'password' => 'password',
    );

    // Authenticate the user
    $user = Sentry::authenticate($credentials, false);
}
catch (Cartalyst\Sentry\Users\LoginRequiredException $e)
{
    echo 'Login field is required.';
}
catch (Cartalyst\Sentry\Users\PasswordRequiredException $e)
{
    echo 'Password field is required.';
}
catch (Cartalyst\Sentry\Users\WrongPasswordException $e)
{
    echo 'Wrong password, try again.';
}
catch (Cartalyst\Sentry\Users\UserNotFoundException $e)
{
    echo 'User was not found.';
}
catch (Cartalyst\Sentry\Users\UserNotActivatedException $e)
{
    echo 'User is not activated.';
}

// The following is only required if the throttling is enabled
catch (Cartalyst\Sentry\Throttling\UserSuspendedException $e)
{
    echo 'User is suspended.';
}
catch (Cartalyst\Sentry\Throttling\UserBannedException $e)
{
    echo 'User is banned.';
}
```

https://cartalyst.com/manual/sentry/2.1#example

**Comment by rsenses** [comment]
Your second example is to authenticate a user, the first one is to save it.

With a simple example everything works as expected:

``` php
<?php
define('VENDOR_DIR', __DIR__ . '/../vendor/'); // Definimos El directorio vhost
define('APP_DIR', __DIR__ . '/../app/'); // Definimos El directorio vhost

// Autoload and Flight Start
require VENDOR_DIR . 'autoload.php';

// Home Route
Flight::route('GET /', function() {
    /*
     *
     * opcode number: 108
     */
    $errorMessage = null;
    try {
        $error = 'Always throw this error';
        throw new \Exception($error);
    } catch (\Exception $e) {
        $errorMessage = 'Caught exception: ' . $e->getMessage() . "\n";
    }

    echo $errorMessage;
    // Continue execution
    echo '<br>Hello World';
});

Flight::start();
```

But with Sentry i always get a 500 error and Flight stop executing:

```
500 Internal Server Error
A user already exists with login [xxx@xxxxxx.com], logins must be unique for users. (0)

#0 /Users/xxxxx/www-nginx/xxxxx/vendor/cartalyst/sentry/src/Cartalyst/Sentry/Users/Eloquent/User.php(315): Cartalyst\Sentry\Users\Eloquent\User->validate()
#1 /Users/xxxxx/www-nginx/xxxxx/app/controllers/users.php(271): Cartalyst\Sentry\Users\Eloquent\User->save()
#2 /Users/xxxxx/www-nginx/xxxxx/app/routes.php(77): Controllers\Users->save('2')
#3 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/core/Dispatcher.php(162): {closure}('2')
#4 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#5 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/Engine.php(312): flight\core\Dispatcher::execute(Object(Closure), Array)
#6 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->_start()
#7 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#8 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#9 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#10 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#11 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->start()
#12 /Users/xxxxx/www-nginx/xxxxx/vendor/mikecao/flight/flight/Flight.php(65): flight\core\Dispatcher::invokeMethod(Array, Array)
#13 /Users/xxxxx/www-nginx/xxxxx/public/index.php(50): Flight::__callStatic('start', Array)
#14 /Users/xxxxx/www-nginx/xxxxx/public/index.php(50): Flight::start()
#15 {main}
```

I'm gona make a test just with Sentry...

**Comment by rsenses** [comment]
I discovered the error, Sentry documentation says:
Cartalyst\Sentry\Users\PasswordRequiredException
but you need to use:
\Cartalyst\Sentry\Users\PasswordRequiredException

thats all... thanks for the help

**Comment by jimlei** [comment]
Great! Yeah if You're in a namespace PHP will try to load the Exception classes in whichever namespace you're in if you don't have that leading slash.

You could add use statements instead, it will also clean up your code

``` php
<?php

namespace App;

use Cartalyst\Sentry\Groups\GroupNotFoundException;
use Cartalyst\Sentry\Users\LoginRequiredException;
use Cartalyst\Sentry\Users\PasswordRequiredException;
use Cartalyst\Sentry\Users\UserExistsException;

class someClass
{
    public function someMethod()
    {
        try
        {
            // Create the user
            $user = Sentry::createUser(array(
                'email'     => 'john.doe@example.com',
                'password'  => 'test',
                'activated' => true,
            ));

            // Find the group using the group id
            $adminGroup = Sentry::findGroupById(1);

            // Assign the group to the user
            $user->addGroup($adminGroup);
        }
        catch (LoginRequiredException $e)
        {
            echo 'Login field is required.';
        }
        catch (PasswordRequiredException $e)
        {
            echo 'Password field is required.';
        }
        catch (UserExistsException $e)
        {
            echo 'User with this login already exists.';
        }
        catch (GroupNotFoundException $e)
        {
            echo 'Group was not found.';
        }
    }
}
```
