### ISSUE TITLE
problem router $Path in Flight::path

### ISSUE THREAD

**Issue by ameralrdadi** [flightphp/core#286]
Hello 

problem router $Path in flight::path($Path)
in server web but in localhost not problem 

thanks.

**Comment by mikecao** [comment]
What is the problem?

**Comment by ameralrdadi** [comment]
Hello Mikecao  

```
500 Internal Server Error

Invalid callback specified. (0)

#0 flight/Engine.php(313): flight\core\Dispatcher::execute(Array, Array)
#1 flight/core/Dispatcher.php(196): flight\Engine->_start()
#2 flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#3 flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#4 flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#5 flight/core/Dispatcher.php(196): flight\Engine->__call('start', Array)
#6 flight/core/Dispatcher.php(196): flight\Engine->start()
#7 flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#8 index.php(7): Flight::__callStatic('start', Array)
#9 index.php(7): Flight::start()
#10 {main}
```

Thanks..

**Comment by mikecao** [comment]
The error says you're passing an invalid callback. Check the function you're passing to your route.
